configfile:"config.json"
ind=config['data']
outd=config['output']
genome=config["reference"]["genome"]
spliceai=config['software']['spliceai']

SAMPLES, =glob_wildcards(ind+"/{sample}.vcf")
rule spliceai_done:
	input:
		expand(outd+"/{sample}"+config["spliceai_suffix"],sample=SAMPLES)
rule spliceai_annotation:
	input:
		vcf=ind+"/{sample}.vcf"
	output:
		outd+"/{sample}"+config["spliceai_suffix"]
	shell:
		"""{spliceai} -I {input.vcf} -O {output} -R {genome} -A grch38"""
